name: CI/CD with Appium

on:
  schedule:
    - cron: '0 16 * * *'  # Scheduled to run every day at 4:00 PM UTC (adjust as needed)

  workflow_dispatch:
   inputs:
      devices:
        description: "Select Device lists"
        required: true
        default: "Android:Samsung Galaxy S22 Ultra:12.0"
        type: choice
        options:
          - "Android:Samsung Galaxy S22 Ultra:12.0"
      app-url:
        description: "bs://546e0ef1089348a188ab63698ac35b6788944f0f"
        required: true
        type: string
             
env:
  BROWSER_STACK_USERNAME: anjanaprakash_hHWeNt
  BROWSER_STACK_ACCESS_KEY: t5KuKWzMqgRpyWCLhm87
  SCHEDULE_DEVICES: Android:Samsung Galaxy S22 Ultra:12.0

jobs:
  run-presto-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
            java-version: "17"
            distribution: "temurin"
            cache: maven
      - name: Run the tests
        run: |
          mvn -q test
        env:
          BROWSER_STACK_HUB_URL: "https://${{ env.BROWSER_STACK_USERNAME }}:${{ env.BROWSER_STACK_ACCESS_KEY }}@hub.browserstack.com/wd/hub"
          DEVICE_DETAILS: "Android:Samsung Galaxy S22 Ultra:12.0"
          APP_URL: "${{ inputs.app-url }}"

      - name: Push test logs to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Test Execution logs
          path: logs/test-appium.log

      - name: Push extent report html file to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Test Execution Result in HTML
          path: ExtentReports/AutomationResult.html
